name: CI

on:
  push:
    branches:
      - staging
      - trying
      - master
  pull_request:
      branches:
        - "**"
      
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install latest rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo bootstrap
        run: cargo bootstrap
      - name: Run cargo build
        run: cargo build --all --verbose
      - name: Run cargo test
        run: cargo test --all --verbose
      - name: Run cargo doc
        run: cargo doc --all --verbose
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install latest rust 1.47.0 toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0 # Pinned warnings
          override: true
          components: rustfmt, clippy
      - name: Check clippy lints
        run: cargo clippy --all -- -D warnings
      - name: Check rustfmt
        run: cargo fmt --all -- --check
  minimal versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install latest rust nightly-2020-01-01 toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-01-01 # Arbitrary nightly for unstable cargo feature -- make this MSRV build later?
          override: true
      - name: Generate lockfile
        run: cargo -Z minimal-versions generate-lockfile
      - name: Run cargo bootstrap
        run: cargo bootstrap
      - name: Run cargo test
        run: cargo test --all --verbose
